version: '3.8'

services:
  bot:
    build: .
    container_name: autoforwardbot
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/Cluster0
      - DB_NAME=Cluster0
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - BOT_TOKEN=${BOT_TOKEN}
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
